Repository sain0136/MyRotaryProjects, pull requests merged in 2023-01, with the labels that each got.

#4 feat: basic file structure set up
  Backend/readme.txt
  Frontend/readme.txt
Labels: Ready To Merge

#5 feat: backend set up with intinial adonis config
  .vscode/launch.json
  Backend/.adonisrc.json
  Backend/.editorconfig
  Backend/.env.example
  Backend/.env.test
  Backend/.gitignore
  Backend/ace
  Backend/ace-manifest.json
  Backend/app/Exceptions/Handler.ts
  Backend/commands/index.ts
  Backend/config/app.ts
  Backend/config/bodyparser.ts
  Backend/config/cors.ts
  Backend/config/drive.ts
  Backend/config/hash.ts
  Backend/contracts/drive.ts
  Backend/contracts/env.ts
  Backend/contracts/events.ts
  Backend/contracts/hash.ts
  Backend/contracts/tests.ts
  Backend/env.ts
  Backend/package-lock.json
  Backend/package.json
  Backend/providers/AppProvider.ts
  Backend/server.ts
  Backend/start/kernel.ts
  Backend/start/routes.ts
  Backend/test.ts
  Backend/tests/bootstrap.ts
  Backend/tests/functional/hello_world.spec.ts
  Backend/tsconfig.json
  Frontend/readme.txt
Labels: Ready To Merge

#12 feat: Scaffolded Frotend Vue Typescript
  Frontend/.gitignore
  Frontend/.vscode/extensions.json
  Frontend/README.md
  Frontend/env.d.ts
  Frontend/index.html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/favicon.ico
  Frontend/src/App.vue
  Frontend/src/assets/base.css
  Frontend/src/assets/logo.svg
  Frontend/src/assets/main.css
  Frontend/src/components/HelloWorld.vue
  Frontend/src/components/TheWelcome.vue
  Frontend/src/components/WelcomeItem.vue
  Frontend/src/components/__tests__/HelloWorld.spec.ts
  Frontend/src/components/icons/IconCommunity.vue
  Frontend/src/components/icons/IconDocumentation.vue
  Frontend/src/components/icons/IconEcosystem.vue
  Frontend/src/components/icons/IconSupport.vue
  Frontend/src/components/icons/IconTooling.vue
  Frontend/src/main.ts
  Frontend/src/router/index.ts
  Frontend/src/stores/counter.ts
  Frontend/src/views/AboutView.vue
  Frontend/src/views/HomeView.vue
  Frontend/tsconfig.app.json
  Frontend/tsconfig.config.json
  Frontend/tsconfig.json
  Frontend/tsconfig.vitest.json
  Frontend/vite.config.ts
Labels: Structural Build

#15 feat:Migration files created and designed
  Backend/.adonisrc.json
  Backend/.env.example
  Backend/ace-manifest.json
  Backend/app/Models/Assset.ts
  Backend/app/Models/Club.ts
  Backend/app/Models/District.ts
  Backend/app/Models/Pledge.ts
  Backend/app/Models/Project.ts
  Backend/app/Models/User.ts
  Backend/config/database.ts
  Backend/database/factories/index.ts
  Backend/database/migrations/1675012802506_districts.ts
  Backend/database/migrations/1675012832926_clubs.ts
  Backend/database/migrations/1675012841637_users.ts
  Backend/database/migrations/1675012853017_projects.ts
  Backend/database/migrations/1675012995215_pledges.ts
  Backend/database/migrations/1675013129445_district_roles.ts
  Backend/database/migrations/1675013132338_club_roles.ts
  Backend/database/migrations/1675017416447_asssets.ts
  Backend/database/seeders/Populate.ts
  Backend/env.ts
  Backend/package-lock.json
  Backend/package.json
  Backend/start/routes.ts
  Backend/tsconfig.json
Labels: Needs Review

#17 feat:controllers made, interfaces made, rotes made
  Backend/ApiCalls.txt
  Backend/app/Controllers/Http/DistrictsController.ts
  Backend/app/Models/Assets.ts
  Backend/app/Models/Club.ts
  Backend/app/Models/Clubs.ts
  Backend/app/Models/District.ts
  Backend/app/Models/Districts.ts
  Backend/app/Models/Pledge.ts
  Backend/app/Models/Pledges.ts
  Backend/app/Models/Project.ts
  Backend/app/Models/Projects.ts
  Backend/app/Models/User.ts
  Backend/app/Models/Users.ts
  Backend/app/Modules/Assets/routes.ts
  Backend/app/Modules/Club/routes.ts
  Backend/app/Modules/District/routes.ts
  Backend/app/Modules/Mail/routes.ts
  Backend/app/Modules/Pledge/routes.ts
  Backend/app/Modules/Project/routes.ts
  Backend/app/Modules/User/routes.ts
  Backend/config/database.ts
  Backend/contracts/BackendInterfaces/Utility.ts
  Backend/contracts/NonPlurizeNamingStrategy.ts
  Backend/contracts/SharedInterfaces/ClubInterface.ts
  Backend/contracts/SharedInterfaces/CustomReponse.ts
  Backend/contracts/SharedInterfaces/DataObject.ts
  Backend/contracts/SharedInterfaces/DistrictInterface.ts
  Backend/contracts/SharedInterfaces/ErrorInterface.ts
  Backend/contracts/SharedInterfaces/ProjectsInterface.ts
  Backend/contracts/SharedInterfaces/UserInterface.ts
  Backend/contracts/SharedInterfaces/UtiltyInterfaces.ts
  Backend/database/migrations/1675012841637_users.ts
  Backend/database/migrations/1675012853017_projects.ts
  Backend/database/migrations/1675012995215_pledges.ts
  Backend/database/migrations/1675013129445_district_roles.ts
  Backend/database/migrations/1675013132338_club_roles.ts
  Backend/database/seeders/Populate.ts
  Backend/start/routes.ts
Labels: Needs Review

#19 Refactor: Just added Version
  Backend/start/routes.ts
Labels: Ready To Merge

#22 Bug: fixed Type error
  Backend/app/Controllers/Http/DistrictsController.ts
  Backend/contracts/SharedInterfaces/ProjectsInterface.ts
Labels: Ready To Merge

#24 Feat:Controllers are half done and shared finished
  Backend/ApiCalls.txt
  Backend/app/Controllers/Http/AssetsController.ts
  Backend/app/Controllers/Http/ClubsController.ts
  Backend/app/Controllers/Http/DistrictsController.ts
  Backend/app/Controllers/Http/MailController.ts
  Backend/app/Controllers/Http/PledgesController.ts
  Backend/app/Controllers/Http/ProjectsController.ts
  Backend/app/Controllers/Http/UploadsController.ts
  Backend/app/Controllers/Http/UsersController.ts
  Backend/app/Models/Projects.ts
  Backend/app/Modules/Club/routes.ts
  Backend/app/Modules/User/routes.ts
  Backend/contracts/BackendInterfaces/RotaryYear.ts
  Backend/contracts/BackendInterfaces/Utility.ts
  Backend/contracts/Shared/FrontEndUtil/UtilityMethods.ts
  Backend/contracts/Shared/SharedClasses/Classes/ClubProject.ts
  Backend/contracts/Shared/SharedClasses/Classes/DistrictObject.ts
  Backend/contracts/Shared/SharedClasses/Classes/DmProject.ts
  Backend/contracts/Shared/SharedClasses/Classes/DsgProject.ts
  Backend/contracts/Shared/SharedClasses/Classes/GenericProject.ts
  Backend/contracts/Shared/SharedClasses/Classes/RotaryClub.ts
  Backend/contracts/Shared/SharedClasses/Classes/RotaryUser.ts
  Backend/contracts/Shared/SharedInterfaces/ClubInterface.ts
  Backend/contracts/Shared/SharedInterfaces/CustomReponse.ts
  Backend/contracts/Shared/SharedInterfaces/DataObject.ts
  Backend/contracts/Shared/SharedInterfaces/DistrictInterface.ts
  Backend/contracts/Shared/SharedInterfaces/ErrorInterface.ts
  Backend/contracts/Shared/SharedInterfaces/ProjectsInterface.ts
  Backend/contracts/Shared/SharedInterfaces/UserInterface.ts
  Backend/contracts/Shared/SharedInterfaces/UtilityInterfaces.ts
  Backend/contracts/SharedInterfaces/ProjectsInterface.ts
  Backend/contracts/SharedInterfaces/UtiltyInterfaces.ts
  Backend/database/migrations/1675012853017_projects.ts
  Backend/database/seeders/Populate.ts
Labels: Needs Review
